language: cpp
compiler: gcc
sudo: require
dist: trusty

script:
  - bash -ex packaging/appimage/make_app_image.sh
  - ls -lh

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh LiberTEM*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
